# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from front_end.grpc import assignService_pb2 as assignService__pb2


class RegionReceiveServiceStub(object):
    """*
    A service that receives a region and assigns it to a domain.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AssignRegion = channel.unary_unary(
                '/RegionReceiveService/AssignRegion',
                request_serializer=assignService__pb2.Region.SerializeToString,
                response_deserializer=assignService__pb2.Acknowledgement.FromString,
                )
        self.ShutDownPod = channel.unary_unary(
                '/RegionReceiveService/ShutDownPod',
                request_serializer=assignService__pb2.Empty.SerializeToString,
                response_deserializer=assignService__pb2.ShutDownMessage.FromString,
                )


class RegionReceiveServiceServicer(object):
    """*
    A service that receives a region and assigns it to a domain.
    """

    def AssignRegion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShutDownPod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegionReceiveServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AssignRegion': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignRegion,
                    request_deserializer=assignService__pb2.Region.FromString,
                    response_serializer=assignService__pb2.Acknowledgement.SerializeToString,
            ),
            'ShutDownPod': grpc.unary_unary_rpc_method_handler(
                    servicer.ShutDownPod,
                    request_deserializer=assignService__pb2.Empty.FromString,
                    response_serializer=assignService__pb2.ShutDownMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RegionReceiveService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RegionReceiveService(object):
    """*
    A service that receives a region and assigns it to a domain.
    """

    @staticmethod
    def AssignRegion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RegionReceiveService/AssignRegion',
            assignService__pb2.Region.SerializeToString,
            assignService__pb2.Acknowledgement.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ShutDownPod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RegionReceiveService/ShutDownPod',
            assignService__pb2.Empty.SerializeToString,
            assignService__pb2.ShutDownMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
