#!/bin/bash


apt install -y build-essential \
                cmake \
                libgflags-dev \
                libsnappy-dev \
                zlib1g-dev \
                libbz2-dev \
                liblz4-dev \
                libzstd-dev