apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: cs6620-fall21-dedup-nodes-back-end
    app.kubernetes.io/component: cs6620-fall21-dedup-nodes-back-end
    app.kubernetes.io/instance: cs6620-fall21-dedup-nodes-back-end
  name: cs6620-fall21-dedup-nodes-back-end
  namespace: cs6620-fall21-intelligentassignment-dedupnodes
spec:
  limits:
    type: "Pod"
    max:
      cpu: "1"
  source:
    contextDir: simulator/back_end
    git:
      uri: https://github.com/yrrah/cs6620-fall21-intelligent-assignment-of-data-to-dedup-nodes.git
    type: Git
  strategy:
    type: Source
    dockerStrategy:
      env:
      - name: SIMULATOR_MODE
        value: DEMO
      - name: APP_FILE
        value: src/back_end/cli.py
  output:
    to:
      kind: ImageStreamTag
      name: cs6620-fall21-dedup-nodes-back-end:latest