apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: cs6620-fall21-dedup-nodes-back-end
  namespace: cs6620-fall21-intelligentassignment-dedupnodes
spec:
  selector:
    app: cs6620-fall21-dedup-nodes-back-end
  template:
    metadata:
      labels:
        app: cs6620-fall21-dedup-nodes-back-end
    spec:
      containers:
        - name: cs6620-fall21-dedup-nodes-back-end
          image: >-
            image-registry.openshift-image-registry.svc:5000/cs6620-fall21-intelligentassignment-dedupnodes/cs6620-fall21-dedup-nodes-back-end
          ports:
            - containerPort: 50051
          env:
            - name: SIMULATOR_MODE
              value: DEMO
            - name: SERVER_IP
              value: 10.217.5.5
#  replicas: 3
