apiVersion: batch/v1
kind: Job
metadata:
  name: cs6620-fall21-dedup-nodes-front-end
  namespace: cs6620-fall21-intelligentassignment-dedupnodes
spec:
  selector:
    app: cs6620-fall21-dedup-nodes-front-end
  template:
    metadata:
      labels:
        app: cs6620-fall21-dedup-nodes-front-end
    spec:
      containers:
        - name: cs6620-fall21-dedup-nodes-front-end
          image: >-
            image-registry.openshift-image-registry.svc:5000/cs6620-fall21-intelligentassignment-dedupnodes/cs6620-fall21-dedup-nodes-front-end
          ports:
            - containerPort: 50051
          env:
            - name: SIMULATOR_MODE
              value: HELLO
      restartPolicy: Never